### PR TITLE
Update dependencies and fix some warnings/typos

### PR DESCRIPTION
**Pull request by Abestanis**
See #36.

### CODE REVIEW

**Comment by Abestanis** [comment]
Looks like the commit 3cdd79ab26e38b9fb2a58cb79996bff891280b23 somehow got duplicated in there, I'm not entirely sure why.

**Comment by Abestanis** [comment]
Awesome, I will start working on pull requests for the other changes.

**Comment by RoelVB** [comment]
Thanks.
I'm also not sure what's wrong with that one commit. Now we have it twice for some reason.

Just FYI. I'm thinking about changing the GUI to React for next version and replace all remaining JQuery for plain JS.

**Comment by Abestanis** [comment]
> Just FYI. I'm thinking about changing the GUI to React for next version and replace all remaining JQuery for plain JS.

Ok, I used JQuery for my changes, but it should be possible to convert that.

**Comment by RoelVB** [comment]
No. Using JQuery is fine for now.

I'll create a v2.0 branch when I'm going to convert it.

**Pull request merged**
