### PR TITLE
Reduce input detection CPU usage

### PR DESCRIPTION
**Pull request by Abestanis**
This reduces the CPU consumption of the FieldSet generation and speeds up the progress.
I measured the runtime of the `detectFields` function:
| Test page | Runtime before the patch | Runtime with the patch | Approximated difference |
| ---------- | ---------------------------- | -------------------------- | ------------ |
| A [simple page](https://github.com/RoelVB/ChromeKeePass/files/7178287/insertedPassword.zip) without password `input`s | `0.319` ± `0.074` ms | `0.136` ± `0.033` ms | `-57`% <br/> (~`2.34`x faster) |
| A complex page with one password `input` ([virustotal.com](https://www.virustotal.com/gui/sign-in)) | `0.322` ± `0.086` ms | `0.133` ± `0.032` ms | `-59`% <br/> (~`2.42`x faster) |

The main improvement is not iterating over all the inputs, but rather searching for previous `input` elements starting from the password `input`s.

### CODE REVIEW

**Comment by Abestanis** [comment]
@RoelVB This is still valid and it still reduces the runtime of the `detectFields` function.
It includes the changes form #90, so this should be merged after it.

**Comment by Abestanis** [comment]
The timings were gathered with the following code changes to `content_script.ts`:
```ts
import $ from 'jquery-slim';

import PageControl from './classes/PageControl';
const pageControl = new PageControl();

$(()=>{
    console.time('detectFields')
    pageControl.detectFields();
    console.timeEnd('detectFields');
    if (pageControl.settings.searchForInputsOnUpdate) // Should the MutationObserver be enabled?
    {
        // The MutationObserver implementation
        const observer = new MutationObserver((mutations) => {
            if (mutations.length == 11) {
                console.time('ChangeObserver')
            }
            for(const mutation of mutations)
            {
                for(const node of mutation.addedNodes)
                {
                    if(node instanceof HTMLElement)
                    {
                        const passwordFields = node.querySelectorAll('input[type="password"]');

                        if(passwordFields.length)
                            setTimeout(() => pageControl.detectNewFields(passwordFields), 100);
                    }
                }
            }
            if (mutations.length == 11) {
                console.timeEnd('ChangeObserver');
            }
        });

        // Start observing
        observer.observe(document.body, {
            childList: true,
            subtree: true,
        });
    }
});
```
The test was performed on https://www.virustotal.com/gui/sign-in by reloading the page multiple times. The unit is milliseconds.

| detectFields [Before] | ChangeObserver [Before] | detectFields [After] | ChangeObserver [After] |
|------------------------|-----------------------------|----------------------|----------------------------|
0.40478515625 | 0.098876953125 | 0.380859375 | 0.137939453125
0.447021484375 | 0.087890625 | 0.13916015625 | 0.059814453125
0.571044921875 | 0.09716796875 | 0.181884765625 | 0.048828125
0.43115234375 | 0.10498046875 | 0.133056640625 | 0.107177734375
0.491943359375 | 0.06103515625 | 0.18505859375 | 0.095703125
0.419921875 | 0.080078125 | 0.202880859375 | 0.15869140625
0.35009765625 | 0.090087890625 | 0.14404296875 | 0.048828125
0.386962890625 | 0.31884765625 | 0.155029296875 | 0.06103515625
0.257080078125 | 0.12109375 | 0.141845703125 | 0.094970703125
0.358154296875 | 0.133056640625 | 0.22802734375 | 0.06298828125
0.365966796875 | 0.0869140625 | 0.13916015625 | 0.114013671875
0.366943359375 | 0.17724609375 | 0.134033203125 | 0.10205078125
0.3779296875 | 0.08984375 | 0.145751953125 | 0.04296875
0.2880859375 | 0.176025390625 | 0.14111328125 | 0.0458984375
0.464111328125 | 0.14892578125 | 0.138916015625 | 0.109130859375
0.359130859375 | 0.063720703125 | 0.202880859375 | 0.06689453125
0.262939453125 | 0.097900390625 | 0.125244140625 | 0.052978515625
0.284912109375 | 0.26611328125 | 0.14306640625 | 0.046875
0.3701171875 | 0.114013671875 | |
0.546875 | 0.051025390625 | |
0.275146484375 | 0.120849609375 | |

The average can be seen in the following table:

|                  | detectFields | ChangeObserver |
|------------|---------------|--------------------|
| **Before** | 0.3848         | 0.1231                  |
| **After**   | 0.1701          | 0.0809                  |
| **Diff**     | ~ -0.2147     | ~ -0.0422             |

**Comment by RoelVB** [comment]
@Abestanis I didn't find time to check you PRs yet. I'll try to check them all this weekend

**Comment by Abestanis** [comment]
No worries, no rush.

**Comment by RoelVB** [comment]
I've made a version of CKP that fully got rid of jQuery a long time ago, which improves performance.
But I decided to not release it, because it contains changes that I don't fully trust to work for 100% and I was planning on rewriting a major part of CKP anyhow.

Also an important part of the rewrite is adding automated tests. Which would make me less hesitant to publish changes like completely getting rid of jQuery. I think we might also get a bèta release of CKP, so we can publish big changes into the bèta first.

If you don't mind I would like to close this PR, since similar/overlapping changes are included in the rewrite.

**Comment by Abestanis** [comment]
> I've made a version of CKP that fully got rid of jQuery

Nice, I hope my other pull requests don't conflict with too much, but luckily they are mostly on the backend, not using JQuery.

> Also an important part of the rewrite is adding automated tests.

That is awesome! 💯

> If you don't mind I would like to close this PR, since similar/overlapping changes are included in the rewrite.

No, makes sense, although it might be good to see if the general idea of this pr can still be applied to your branch in the future.
The main improvement comes from not searching through all inputs on the site for each password field, instead just look for the closest input element before the password input by walking the html element tree. The main function, `_getPreviousInput`, doesn't use any JQuery if I see that correctly, so you could just copy it over to your branch.

**Pull request closed without merging**
